# Build Module Workflow Configuration
name: create-module
description: "Interactive workflow to build complete XIAOMA modules with agents, workflows, tasks, and installation infrastructure"
author: "XiaoMa"

# Critical variables load from config_source
config_source: "{project-root}/{xiaoma_folder}/xmb/config.yaml"
custom_module_location: "{config_source}:custom_module_location"
communication_language: "{config_source}:communication_language"
user_name: "{config_source}:user_name"

# Reference guides for module building
module_structure_guide: "{installed_path}/module-structure.md"
installer_templates: "{installed_path}/installer-templates/"

# Use existing build workflows
agent_builder: "{project-root}/{xiaoma_folder}/xmb/workflows/create-agent/workflow.yaml"
workflow_builder: "{project-root}/{xiaoma_folder}/xmb/workflows/create-workflow/workflow.yaml"
brainstorming_workflow: "{project-root}/{xiaoma_folder}/core/workflows/brainstorming/workflow.yaml"
brainstorming_context: "{installed_path}/brainstorm-context.md"

# Reference examples - for learning patterns
xmc_module_dir: "{project-root}/{xiaoma_folder}/xmc/"
cis_module_dir: "{project-root}/{xiaoma_folder}/cis/"
existing_agents_dir: "{project-root}/{xiaoma_folder}/*/agents/"
existing_workflows_dir: "{project-root}/{xiaoma_folder}/*/workflows/"

# Optional user inputs - discovered if they exist
input_file_patterns:
  module_brief:
    description: "Module brief with vision and requirements (optional)"
    whole: "{output_folder}/module-brief-*.md"
    load_strategy: "FULL_LOAD"
  brainstorming:
    description: "Brainstorming session outputs (optional)"
    whole: "{output_folder}/brainstorming-*.md"
    load_strategy: "FULL_LOAD"

# Module path and component files
installed_path: "{project-root}/{xiaoma_folder}/xmb/workflows/create-module"
template: false # This is an interactive scaffolding workflow
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Output configuration - creates entire module structure
# Save to custom_module_location/{{module_code}}
installer_output_folder: "{custom_module_location}/{{module_code}}"

standalone: true

# Web bundle configuration
web_bundle: false # XMB workflows run locally in XIAOMA-CLI project
