# Start Enhanced Workflow Task
# 启动增强工作流任务

meta:
  name: "Start Enhanced Workflow"
  description: "启动全流程自动化增强工作流系统"
  version: "2.0"
  created_date: "2025-09-10"
  tags: ["workflow", "automation", "quality"]

# ========== 任务配置 ==========
task:
  name: "start-enhanced-workflow"
  aliases:
    - "enhanced-workflow"
    - "start-full-quality-automation"
    - "activate-enhanced-system"
  category: "automation"
  complexity: "high"
  estimated_duration: "60-120 minutes"

# ========== 任务描述 ==========
description: |
  启动基于多层质量保证的增强工作流系统。该系统提供：

  🎯 **核心功能**:
  - 全流程自动化文档处理
  - 7层质量验证系统
  - 智能模板理解和适配
  - 自动错误检测和纠正
  - 实时进度监控和报告

  🛡️ **质量保证**:
  - 语法格式验证 (100%通过率)
  - 内容完整性验证 (≥90%标准)
  - 内容质量验证 (≥87%标准)
  - 一致性验证 (≥96%标准)
  - 实施可行性验证 (≥83%标准)
  - 业务价值验证 (≥82%标准)
  - 最终集成验证 (≥90%标准)

  ⚡ **执行特性**:
  - 并行处理优化
  - 自动纠错机制
  - 回滚和恢复能力
  - 零容错质量标准

# ========== 执行流程 ==========
execution:
  # 前置检查
  pre_checks:
    - check_system_requirements
    - validate_project_structure
    - verify_template_accessibility
    - confirm_write_permissions

  # 主要执行步骤
  main_steps:
    - step: "system_initialization"
      description: "系统初始化"
      agent: "master-execution-engine"
      timeout: 600
      actions:
        - "加载项目上下文"
        - "初始化质量验证系统"
        - "验证模板理解能力"
        - "设置质量门控"
      success_criteria:
        - "所有系统组件正常"
        - "模板理解验证通过"
        - "质量系统就绪"

    - step: "intelligent_planning"
      description: "智能任务规划"
      agent: "enhanced-workflow-orchestrator"
      timeout: 900
      actions:
        - "分析项目范围和需求"
        - "识别任务依赖关系"
        - "优化执行策略"
        - "配置并行处理"
      success_criteria:
        - "任务分析完成"
        - "执行策略优化"
        - "质量保证规划就绪"

    - step: "template_adaptation"
      description: "模板智能适配"
      agent: "intelligent-template-adapter"
      timeout: 600
      actions:
        - "深度理解模板结构"
        - "验证模板理解正确性"
        - "准备内容生成引擎"
        - "配置质量检查规则"
      success_criteria:
        - "模板理解100%准确"
        - "内容生成引擎就绪"
        - "质量规则配置完成"

    - step: "batch_processing"
      description: "批量文档处理"
      agent: "automated-quality-validator"
      timeout: 2400
      parallel: true
      batch_size: 3
      actions:
        - "执行7层质量验证"
        - "自动内容生成和增强"
        - "实时错误检测和纠正"
        - "生成质量报告"
      success_criteria:
        - "所有质量层验证通过"
        - "文档格式完全合规"
        - "内容质量达标"

    - step: "integration_validation"
      description: "集成验证"
      agent: "master-execution-engine"
      timeout: 1500
      actions:
        - "跨文档一致性验证"
        - "全局质量评估"
        - "集成测试执行"
        - "最终质量认证"
      success_criteria:
        - "全局一致性达标"
        - "集成测试通过"
        - "质量认证颁发"

    - step: "delivery_preparation"
      description: "交付准备"
      agent: "master-execution-engine"
      timeout: 900
      actions:
        - "生成综合报告"
        - "准备交付包"
        - "更新项目文档"
        - "完成质量认证"
      success_criteria:
        - "交付包完整"
        - "质量认证完成"
        - "实施就绪确认"

# ========== 质量门控 ==========
quality_gates:
  gate_1_system_ready:
    name: "系统就绪验证"
    criteria:
      - "all_components_operational"
      - "template_understanding_verified"
      - "quality_system_initialized"
    failure_action: "ABORT_WITH_DIAGNOSTICS"

  gate_2_planning_complete:
    name: "规划完成验证"
    criteria:
      - "task_analysis_validated"
      - "strategy_feasibility_confirmed"
      - "qa_readiness_validated"
    failure_action: "REPLANNING_CYCLE"

  gate_3_template_ready:
    name: "模板就绪验证"
    criteria:
      - "template_comprehension_100_percent"
      - "content_generation_engine_ready"
      - "quality_rules_configured"
    failure_action: "TEMPLATE_RE_ANALYSIS"

  gate_4_quality_validation:
    name: "质量验证通过"
    criteria:
      - "all_7_layers_passed"
      - "quality_scores_meet_thresholds"
      - "zero_critical_errors"
    failure_action: "ITERATIVE_IMPROVEMENT"

  gate_5_integration_success:
    name: "集成验证成功"
    criteria:
      - "global_consistency_achieved"
      - "integration_tests_passed"
      - "delivery_readiness_confirmed"
    failure_action: "COMPREHENSIVE_REFINEMENT"

# ========== 错误处理 ==========
error_handling:
  error_categories:
    critical_errors:
      items:
        - "system_initialization_failure"
        - "template_understanding_failure"
        - "quality_gate_critical_failure"
      actions: "IMMEDIATE_STOP_AND_REPORT"

    recoverable_errors:
      items:
        - "quality_threshold_not_met"
        - "content_completeness_issues"
        - "consistency_problems"
      actions: "AUTO_CORRECTION_CYCLE"

    warning_conditions:
      items:
        - "performance_degradation"
        - "resource_constraints"
        - "timeout_approaching"
      actions: "LOG_AND_CONTINUE_WITH_MONITORING"

  recovery_strategies:
    - "checkpoint_rollback"
    - "selective_retry"
    - "alternative_path_execution"
    - "graceful_degradation"

# ========== 输出规范 ==========
output_specification:
  primary_outputs:
    - name: "enhanced_user_stories"
      location: "docs/stories/"
      format: "ENHANCED_MARKDOWN"
      description: "增强格式的用户故事文档"

    - name: "quality_certification_report"
      location: "reports/quality/"
      format: "MARKDOWN_WITH_METRICS"
      description: "全面的质量认证报告"

    - name: "implementation_readiness_certificate"
      location: "certificates/"
      format: "STRUCTURED_DOCUMENT"
      description: "实施就绪认证书"

  secondary_outputs:
    - name: "execution_log"
      location: "logs/"
      format: "STRUCTURED_LOG"
      description: "详细的执行日志"

    - name: "performance_metrics"
      location: "metrics/"
      format: "JSON"
      description: "性能指标数据"

    - name: "improvement_recommendations"
      location: "recommendations/"
      format: "MARKDOWN"
      description: "持续改进建议"

# ========== 用户交互 ==========
user_interaction:
  interaction_points:
    pre_execution:
      - confirm_execution_mode
      - review_quality_thresholds
      - approve_batch_configuration

    during_execution:
      - display_real_time_progress
      - show_quality_gate_status
      - alert_on_critical_issues

    post_execution:
      - present_quality_summary
      - confirm_delivery_acceptance
      - provide_improvement_recommendations

  customization_options:
    execution_mode:
      options: ["MAXIMUM_QUALITY", "BALANCED_EFFICIENCY", "RAPID_DELIVERY"]
      default: "MAXIMUM_QUALITY"
      description: "选择执行模式以平衡质量和效率"

    batch_size:
      options: [1, 3, 5]
      default: 3
      description: "设置并行处理批次大小"

    quality_thresholds:
      adjustable: true
      min_values:
        overall_quality: 80
        template_compliance: 100
        content_completeness: 80
      default_values:
        overall_quality: 90
        template_compliance: 100
        content_completeness: 90

# ========== 成功标准 ==========
success_criteria:
  mandatory_requirements:
    - "all_quality_gates_passed"
    - "zero_critical_errors"
    - "template_compliance_100_percent"
    - "implementation_readiness_achieved"

  quality_thresholds:
    overall_quality_score: 90
    template_compliance_rate: 100
    content_completeness_rate: 90
    consistency_score: 95
    implementation_feasibility_score: 85
    business_value_alignment_score: 80

  deliverable_requirements:
    - "all_user_stories_enhanced"
    - "quality_certification_issued"
    - "implementation_guide_complete"
    - "continuous_improvement_plan_provided"

# ========== 使用示例 ==========
usage_examples:
  basic_usage: |
    # 启动增强工作流
    *start-enhanced-workflow

  with_options: |
    # 使用自定义配置启动
    *start-enhanced-workflow --mode=MAXIMUM_QUALITY --batch-size=3 --parallel=true

  quick_start: |
    # 快速启动（使用默认配置）
    *enhanced-workflow

# ========== 预期效果 ==========
expected_outcomes:
  quality_improvements:
    - "零格式错误和结构缺陷"
    - "90%以上的整体质量分数"
    - "100%的模板合规性"
    - "95%以上的跨文档一致性"

  efficiency_gains:
    - "99%的自动化处理率"
    - "减少90%的人工返工需求"
    - "提高60%的文档处理速度"
    - "实现全程可视化监控"

  business_value:
    - "开发就绪的交付成果"
    - "完整的质量认证文档"
    - "详细的实施指导"
    - "持续改进建议"
