name: create-excalidraw-dataflow
description: "Create data flow diagrams (DFD) in Excalidraw format"
author: "XiaoMa"

# Config values
config_source: "{project-root}/{xiaoma_folder}/xmc/config.yaml"
output_folder: "{config_source}:output_folder"

# Workflow components
installed_path: "{project-root}/{xiaoma_folder}/xmc/workflows/diagrams/create-dataflow"
shared_path: "{project-root}/{xiaoma_folder}/xmc/workflows/diagrams/_shared"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Core Excalidraw resources (universal knowledge)
helpers: "{project-root}/{xiaoma_folder}/core/resources/excalidraw/excalidraw-helpers.md"
json_validation: "{project-root}/{xiaoma_folder}/core/resources/excalidraw/validate-json-instructions.md"

# Domain-specific resources (technical diagrams)
templates: "{shared_path}/excalidraw-templates.yaml"
library: "{shared_path}/excalidraw-library.json"

# Output file (respects user's configured output_folder)
default_output_file: "{output_folder}/diagrams/dataflow-{timestamp}.excalidraw"

standalone: true
web_bundle: false
