# Workflow Init - Initial Project Setup
name: workflow-init
description: "Initialize a new XMC project by determining level, type, and creating workflow path"
author: "XiaoMa"

# Critical variables from config
config_source: "{project-root}/{xiaoma_folder}/xmc/config.yaml"
output_folder: "{config_source}:output_folder"
sprint_artifacts: "{config_source}:sprint_artifacts"
user_name: "{config_source}:user_name"
project_name: "{config_source}:project_name"
communication_language: "{config_source}:communication_language"
document_output_language: "{config_source}:document_output_language"
user_skill_level: "{config_source}:user_skill_level"
date: system-generated

# Workflow components
installed_path: "{project-root}/{xiaoma_folder}/xmc/workflows/workflow-status/init"
instructions: "{installed_path}/instructions.md"
template: "{project-root}/{xiaoma_folder}/xmc/workflows/workflow-status/workflow-status-template.yaml"

# Path data files
path_files: "{project-root}/{xiaoma_folder}/xmc/workflows/workflow-status/paths/"

# Output configuration
default_output_file: "{output_folder}/xmc-workflow-status.yaml"

standalone: true
web_bundle: false
