# Quick-Flow: Quick-Dev
name: quick-dev
description: "Flexible development - execute tech-specs OR direct instructions with optional planning."
author: "XiaoMa"

# Config
config_source: "{project-root}/{xiaoma_folder}/xmc/config.yaml"
output_folder: "{config_source}:output_folder"
sprint_artifacts: "{config_source}:sprint_artifacts"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
user_skill_level: "{config_source}:user_skill_level"
date: system-generated

# Project context
project_context: "**/project-context.md"

# Workflow components
installed_path: "{project-root}/{xiaoma_folder}/xmc/workflows/xiaoma-quick-flow/quick-dev"
instructions: "{installed_path}/instructions.md"
checklist: "{installed_path}/checklist.md"

# Related workflows
create_tech_spec_workflow: "{project-root}/{xiaoma_folder}/xmc/workflows/xiaoma-quick-flow/create-tech-spec/workflow.yaml"
party_mode_exec: "{project-root}/{xiaoma_folder}/core/workflows/party-mode/workflow.md"
advanced_elicitation: "{project-root}/{xiaoma_folder}/core/tasks/advanced-elicitation.xml"

standalone: true
web_bundle: false
