# <!-- Powered by XIAOMA™ Core -->
name: bmad-2d-unity-game-dev
version: 1.6.0
short-title: Unity C# 2D Game Dev Pack
description: 2D Game Development expansion pack for XiaoMa Cli - Unity & C# focused
author: pbean (PinkyD)
slashPrefix: bmad2du
