# <!-- Powered by XIAOMA™ Core -->
workflow:
  id: enhanced-fullstack-with-database
  name: Enhanced Full-Stack Development with Database Design
  description: >-
    Enhanced agent workflow for building full-stack applications with comprehensive database design phase.
    Includes MCP MySQL integration for existing database analysis and automated code generation.
  type: greenfield
  project_types:
    - web-app
    - saas
    - enterprise-app
    - data-driven-app
    - api-first

  sequence:
    - agent: analyst
      creates: project-brief.md
      optional_steps:
        - brainstorming_session
        - market_research_prompt
      notes: "Can do brainstorming first, then optional deep research before creating project brief. SAVE OUTPUT: Copy final project-brief.md to your project's docs/ folder."

    - agent: pm
      creates: prd.md
      requires: project-brief.md
      notes: "Creates PRD from project brief using prd-tmpl. SAVE OUTPUT: Copy final prd.md to your project's docs/ folder."

    - agent: database-architect
      action: analyze_existing_database
      creates: existing-database-analysis.md
      condition: has_existing_database
      notes: |
        Connect to MySQL via MCP service and analyze existing database:
        - Check if docs/database/{project_name}-database.md exists
        - If not, connect to database and generate complete documentation
        - If exists, verify and update with current database state
        SAVE OUTPUT: Copy to docs/database/{project_name}-database.md

    - agent: database-architect
      creates: database-design.md
      requires:
        - prd.md
        - existing-database-analysis.md (if exists)
      notes: |
        Design database architecture based on requirements:
        - Identify entities from PRD
        - Design table structures
        - Define relationships and constraints
        - Create ER diagrams
        - Generate optimization strategies
        SAVE OUTPUT: Copy to docs/database/database-design.md

    - agent: database-architect
      action: generate_ddl_dml
      creates: database-scripts/
      requires: database-design.md
      notes: |
        Generate executable SQL scripts:
        - DDL: CREATE TABLE statements with indexes and constraints
        - DML: Initial data and sample queries
        - Migration scripts if updating existing database
        SAVE OUTPUT: Copy to docs/database/scripts/

    - agent: database-architect
      action: generate_entities_and_mappers
      creates: generated-code/
      requires: database-design.md
      notes: |
        Generate Java/Spring code:
        - POJO entity classes with Lombok annotations
        - DTO classes for data transfer
        - MyBatis Mapper interfaces
        - MyBatis XML mapping files
        - Service interfaces and implementations
        - RESTful Controller classes
        SAVE OUTPUT: Copy to src/main/java/{package}/

    - agent: ux-expert
      creates: front-end-spec.md
      requires:
        - prd.md
        - database-design.md
      optional_steps:
        - user_research_prompt
      notes: "Creates UI/UX specification considering data models. SAVE OUTPUT: Copy to docs/front-end-spec.md"

    - agent: architect
      creates: fullstack-architecture.md
      requires:
        - prd.md
        - database-design.md
        - front-end-spec.md
      optional_steps:
        - technical_research_prompt
        - review_generated_code_structure
      notes: |
        Creates comprehensive architecture integrating:
        - Database layer design
        - Generated entity and mapper code
        - API layer design
        - Frontend architecture
        May suggest changes to PRD or database design.
        SAVE OUTPUT: Copy to docs/fullstack-architecture.md

    - agent: pm
      updates: prd.md (if needed)
      requires: fullstack-architecture.md
      condition: architecture_suggests_changes
      notes: "If architect suggests story changes, update PRD and re-export to docs/"

    - agent: database-architect
      updates: database-design.md (if needed)
      requires: fullstack-architecture.md
      condition: architecture_suggests_database_changes
      notes: "If architect suggests database changes, update design and regenerate scripts"

    - agent: po
      validates: all_artifacts
      uses: po-master-checklist
      quality_gates:
        - "system_health_check"
        - "template_understanding_verified"
        - "layer_1_syntax_format_validation"
        - "layer_2_content_completeness_validation"
        - "layer_3_content_quality_validation"
        - "layer_4_consistency_validation"
        - "layer_5_implementation_feasibility_validation"
        - "layer_6_business_value_validation"
      notes: |
        Enhanced validation with multi-layer quality assurance:
        - Database design consistency (95% threshold)
        - API alignment with database (100% compliance)
        - Generated code quality (90% threshold)
        - Content completeness validation
        - Implementation feasibility assessment
        - Business value alignment verification
        May require updates to any document.

    - agent: various
      updates: any_flagged_documents
      condition: po_checklist_issues
      notes: "Fix issues and re-export updated documents to docs/"

    - agent: po
      action: shard_documents
      creates: sharded_docs
      requires: all_artifacts_in_project
      notes: |
        Shard documents for IDE development:
        - PRD sharding
        - Architecture sharding
        - Database design sharding
        Creates organized story structure.

    - agent: sm
      action: create_enhanced_story_with_database
      creates: story.md
      requires:
        - sharded_docs
        - database-design.md
        - generated-code/
      repeats: for_each_epic
      template: enhanced-story-with-database-tmpl.yaml
      quality_gates:
        - "template_compliance_100_percent"
        - "content_structure_validation"
        - "database_integration_validation"
      timeout: 1800 # 30 minutes per story
      retry: 3
      notes: |
        Enhanced story creation with comprehensive database and API integration:
        - Use enhanced-story-with-database-tmpl.yaml template
        - Include detailed database entity mappings
        - Define complete API specifications with request/response examples
        - Reference generated entity classes and mappers
        - Provide data mapping relationships
        - Include comprehensive testing requirements
        - Apply quality validation with 100% template compliance
        Story starts in "Draft" status

    - agent: dev
      action: implement_story
      creates: implementation_files
      requires:
        - story.md
        - generated-code/
      quality_gates:
        - "implementation_quality_check"
        - "code_structure_validation"
        - "api_integration_validation"
      auto_correction:
        max_attempts: 3
        correction_strategies:
          - "immediate_auto_correction"
          - "iterative_quality_improvement"
      notes: |
        Dev implementation using generated code with quality assurance:
        - Use generated entities and mappers
        - Implement business logic with quality validation
        - Connect frontend to APIs with integration checks
        - Apply automated quality corrections when needed
        Updates File List and marks story as "Review"

    - agent: qa
      action: review_implementation
      updates: implementation_files
      requires: implementation_files
      optional: true
      quality_gates:
        - "layer_7_final_integration_validation"
        - "global_consistency_validation"
        - "delivery_readiness_validation"
      quality_standards:
        overall_quality_score: 90
        implementation_feasibility: 85
        integration_completeness: 95
      retry_policy:
        max_retries: 3
        retry_delay: 60
      notes: |
        Enhanced QA review with comprehensive quality validation:
        - Database query performance (performance benchmarks)
        - API contract validation (100% compliance)
        - Data integrity checks (comprehensive validation)
        - Integration testing with quality gates
        - Global consistency validation
        - Final delivery readiness assessment
        Updates story status with quality certification

    - step: repeat_development_cycle
      action: continue_for_all_stories
      notes: "Repeat story cycle for all epic stories"

    - agent: po
      action: epic_retrospective
      creates: epic-retrospective.md
      condition: epic_complete
      optional: true
      notes: "Validate epic completion including database implementation"

    - step: workflow_end
      action: project_complete
      notes: |
        Project complete with:
        - Fully designed database
        - Generated code foundation
        - Implemented business logic
        - Tested integrations

  flow_diagram: |
    ```mermaid
    graph TD
        A[Start] --> B[analyst: project-brief]
        B --> C[pm: prd.md]
        C --> D{Existing DB?}
        D -->|Yes| E[db-architect: analyze existing]
        D -->|No| F[db-architect: design database]
        E --> F
        F --> G[db-architect: generate DDL/DML]
        G --> H[db-architect: generate code]
        H --> I[ux-expert: front-end-spec]
        I --> J[architect: fullstack-architecture]
        J --> K{Changes needed?}
        K -->|Yes| L[Update PRD/DB]
        K -->|No| M[po: validate all]
        L --> M
        M --> N{Issues?}
        N -->|Yes| O[Fix issues]
        N -->|No| P[po: shard docs]
        O --> M
        P --> Q[Development Cycle]
        Q --> R[sm: create story]
        R --> S[dev: implement]
        S --> T[qa: review]
        T --> U{More stories?}
        U -->|Yes| R
        U -->|No| V[Complete]

        style F fill:#FFE4B5
        style G fill:#FFE4B5
        style H fill:#FFE4B5
        style P fill:#ADD8E6
        style R fill:#ADD8E6
        style S fill:#ADD8E6
        style V fill:#90EE90
    ```

  decision_guidance:
    when_to_use:
      - Data-driven applications
      - Applications with complex database requirements
      - Need for automated code generation
      - Existing database integration
      - API-first development approach
      - Enterprise applications with strict data models

  handoff_prompts:
    analyst_to_pm: "Project brief complete. Save as docs/project-brief.md, then create PRD."
    pm_to_database: "PRD ready. Save as docs/prd.md. Database Architect, please analyze requirements and design database."
    database_analysis: "Connecting to MySQL via MCP to analyze existing database structure..."
    database_to_code: "Database design complete. Generating entity classes, mappers, and API code..."
    database_to_ux: "Database design and code generation complete. UX Expert, please create UI specs considering data models."
    ux_to_architect: "UI/UX spec complete. Architect, please create fullstack architecture integrating database layer."
    architect_review: "Architecture complete. Any changes needed to PRD or database design?"
    po_validation: "All artifacts ready including database scripts and generated code. Validating with enhanced quality assurance..."
    quality_validation: "Applying multi-layer quality validation with automated correction capabilities..."
    complete: "Project planning complete with database design, code generation, and quality certification. Ready for development."

# ========== 质量保证配置 ==========
quality_assurance:
  # 质量门控配置
  quality_gates:
    critical_gates:
      - "system_health_check"
      - "template_understanding_verified"
      - "layer_1_syntax_format_validation"
      - "global_consistency_validation"
      - "delivery_readiness_final_validation"

    failure_handling:
      critical_failure: "IMMEDIATE_STOP_AND_CORRECTION"
      quality_failure: "AUTOMATED_CORRECTION_CYCLE"
      integration_failure: "COMPREHENSIVE_REFINEMENT"

  # 质量标准
  quality_standards:
    overall_quality_score: 90
    template_compliance: 100
    content_completeness: 90
    consistency_score: 95
    implementation_feasibility: 85
    business_value_alignment: 80
    database_design_quality: 95
    api_integration_quality: 90

  # 自动纠错配置
  auto_correction:
    max_attempts: 3
    correction_strategies:
      - "immediate_auto_correction"
      - "iterative_quality_improvement"
      - "comprehensive_refinement_cycle"
    rollback_on_failure: true

# ========== 并行处理配置 ==========
parallel_processing:
  enabled: true
  max_concurrent_tasks: 5
  batch_configuration:
    batch_size: 3
    batch_timeout: 2400 # 40分钟每批
    inter_batch_delay: 60 # 1分钟间隔

# ========== 监控和报告 ==========
monitoring_and_reporting:
  real_time_monitoring:
    enabled: true
    update_frequency: "REAL_TIME"
    metrics:
      - "phase_progress"
      - "quality_scores"
      - "database_design_progress"
      - "code_generation_status"
      - "error_detection"
      - "correction_activity"
      - "performance_metrics"

  reporting:
    executive_summary: true
    detailed_technical_report: true
    database_design_report: true
    code_generation_report: true
    quality_certification: true
    continuous_improvement_recommendations: true

  notifications:
    progress_updates: true
    quality_alerts: true
    database_alerts: true
    completion_notifications: true
    error_notifications: true

# ========== 错误处理和恢复 ==========
error_handling:
  retry_policy:
    max_retries: 3
    retry_delay: 60 # 1分钟
    exponential_backoff: true

  rollback_policy:
    checkpoint_frequency: "EVERY_MAJOR_STEP"
    rollback_triggers:
      - "critical_failure"
      - "quality_failure_threshold_exceeded"
      - "database_design_failure"
      - "code_generation_failure"
      - "timeout_exceeded"

  recovery_mechanisms:
    - "checkpoint_rollback"
    - "partial_recovery"
    - "database_design_recovery"
    - "code_regeneration"
    - "full_restart"

# ========== 成功标准 ==========
success_criteria:
  technical_criteria:
    all_quality_gates_passed: true
    overall_quality_score_achieved: true
    zero_critical_errors: true
    template_compliance_100_percent: true
    database_design_validated: true
    code_generation_successful: true

  business_criteria:
    implementation_readiness: true
    documentation_completeness: true
    stakeholder_acceptance: true
    database_performance_validated: true

  process_criteria:
    execution_within_timeframe: true
    resource_utilization_optimized: true
    quality_standards_maintained: true
    database_integration_successful: true
